# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('streetAddress', models.CharField(max_length=100)),
                ('phoneNumber', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
