# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('streetAddress', models.CharField(max_length=100)),
                ('phoneNumber', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Negocios',
                'verbose_name': 'Negocio',
            },
        ),
    ]
