# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Negocios', '0002_auto_20161114_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='neogocio_cliente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
