# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('cards', models.CharField(blank=True, max_length=30, null=True)),
                ('plan', models.CharField(blank=True, max_length=30, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holi', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
