# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
