# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_cliente_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
