# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20161111_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='cliente',
            name='city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='country',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='state',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='street',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='szip',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cards',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
