# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20161122_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
