# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('ropa', 'Ropa'), ('alimento', 'Alimentos'), ('electronicos', 'Electronicos')], default='ropa', max_length=15),
        ),
    ]
