# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventarios', '0001_initial'),
        ('Negocios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_negocio', to='Negocios.Negocio'),
        ),
    ]
