# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('Inventarios', '0001_initial'),
        ('Negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(choices=[('MXN', 'Mexican Peso'), ('USD', 'American Dollar')], default=False, max_length=25)),
                ('quantity', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_negocio', to='Negocios.Negocio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_cliente', to='login.Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_producto', to='Inventarios.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('eventtime', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_negocio', to='Negocios.Negocio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_cliente', to='login.Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_transaction', to='Inventarios.Producto')),
            ],
        ),
    ]
