# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negocios', '0003_negocio_owner'),
        ('Transacciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cliente',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='producto',
            new_name='product',
        ),
        migrations.AddField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_negocio', to='Negocios.Negocio'),
            preserve_default=False,
        ),
    ]
