# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0002_auto_20161115_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(choices=[('MXN', 'Mexican Peso'), ('USD', 'American Dollar')], default=False, max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('demail', models.EmailField(max_length=254)),
                ('itemName', models.CharField(max_length=30)),
                ('itemdescription', models.CharField(max_length=50)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('FOOD', 'Comida'), ('CLO', 'Ropa')], max_length=20)),
                ('street1', models.CharField(max_length=50)),
                ('street2', models.CharField(max_length=30)),
                ('colonia', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('szip', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('bemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
