# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negocios', '0003_negocio_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transacciones', '0003_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_negocio', to='Negocios.Negocio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_cliente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
