# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0002_producto_business'),
        ('Transacciones', '0004_auto_20161122_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_producto', to='Inventarios.Producto'),
            preserve_default=False,
        ),
    ]
