# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0005_checkout_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
