# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('eventtime', models.DateTimeField(auto_now=True)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_transaction', to='Inventarios.Producto')),
            ],
        ),
    ]
