# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0005_auto_20161114_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='idcliente',
        ),
    ]
