# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Compras', '0006_remove_transaction_idcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='idcliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_transaction', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
