# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0008_auto_20161114_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='idcliente',
            new_name='idCliente',
        ),
    ]
